plugins { id "com.android.application" }

android {
    namespace "io.github.playmakerino.tv"
    compileSdk 34
    defaultConfig {
        applicationId "io.github.playmakerino.tv"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
    lint { checkReleaseBuilds false }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
